const images = {
    ['Sunny']: '/public/icons/sun.svg',
    ['Clear']: '/public/icons/sun.svg',
    ['Partly Cloudy']: '/public/icons/minicloud.svg',
    ['Cloudy']: '/public/icons/cloud.svg',
    ['Overcast']: '/public/icons/cloud.svg',
    ['Mist']: '/public/icons/osadki.svg',
    ['Patchy rain possible']: '/public/icons/sunrain.svg',
    ['Patchy snow possible']: '',
    ['Patchy sleet possible']: '',
    ['Patchy freezing drizzle possible']: '',
    ['Thundery outbreaks possible']: '/public/icons/rain.svg',
    ['Blowing snow']: '',
    ['Blizzard']: '/public/icons/wind.svg',
    ['Fog']: '/public/icons/osadki.svg',
    ['Freezing fog']: '/public/icons/osadki.svg',
    ['Patchy light drizzle']: '',
    ['Light drizzle']: '',
    ['Freezing drizzle']: '',
    ['Heavy freezing drizzle']: '',
    ['Patchy light rain']: '/public/icons/sunrain.svg',
    ['Light rain']: '/public/icons/sunrain.svg',
    ['Moderate rain at times']: '/public/icons/minicloud.svg',
    ['Moderate rain']: '/public/icons/minicloud.svg',
    ['Heavy rain at times']: '/public/icons/rain.svg',
    ['Heavy rain']: '/public/icons/rain.svg',
    ['Light freezing rain']: '/public/icons/rain.svg',
    ['Moderate or heavy freezing rain']: '/public/icons/rain.svg',
    ['Light sleet']: '',
    ['Moderate or heavy sleet']: '',
    ['Patchy light snow']: '',
    ['Light snow']: '',
    ['Patchy moderate snow']: '',
    ['Moderate snow']: '',
    ['Patchy heavy snow']: '',
    ['Heavy snow']: '',
    ['Ice pellets']: '',
    ['Light rain shower']: '/public/icons/rain.svg',
    ['Moderate or heavy rain shower']: '/public/icons/rain.svg',
    ['Torrential rain shower']: '/public/icons/rain.svg',
    ['Light sleet showers']: '',
    ['Moderate or heavy sleet showers']: '',
    ['Light snow showers']: '',
    ['Moderate or heavy snow showers']: '',
    ['Light showers of ice pellets']: '',
    ['Moderate or heavy showers of ice pellets']: '',
    ['Patchy light rain with thunder']: '/public/icons/rain.svg',
    ['Moderate or heavy rain with thunder']: '/public/icons/rain.svg',
    ['Patchy light snow with thunder']: '',
    ['Moderate or heavy snow with thunder']: ''
}

export const getImage = (condition) => {
    return images[condition]
}